Tutor.UI/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using Tutor.UI.ViewModels;
using Model;

namespace Tutor.UI.Controllers
{
    public class StudentController : Controller
    {
        StudentService studentSer = new StudentService();
        TaskService taskSer = new TaskService();
        IndentService indentSer = new IndentService();
        AppointmentService appoSer = new AppointmentService();
        TeacherInfoService teacSer = new TeacherInfoService();
        // GET: Student
        public ActionResult Index()
        {
            var sid = (int)Session["user_id"];
            var stu = studentSer.GetModels(b => b.Student_id == sid).FirstOrDefault();
            var task = taskSer.GetModels(b => b.Student_id == sid);
            var task_id = task.Select(b => b.Task_id);
            SdetailVM sdetailvm = new SdetailVM();
            List<TeacherInfo> tea = new List<TeacherInfo>();
            //SelectList s = new SelectList();
            foreach (var item in task_id)
            {
                var appoinfo = appoSer.GetModels(b => b.Task_id == item);
                var teacher_id = appoinfo.Select(b => b.Teacher_id).ToList();
                foreach(var items in teacher_id)
                {
                    var info = teacSer.GetModels(b => b.Teaher_id == items).FirstOrDefault();
                    tea.Add(info);
                }
            }
            var indent = indentSer.GetModels(b => b.Student_id == sid);
            sdetailvm.student = stu;
            sdetailvm.task = task;
            sdetailvm.indent = indent;
            ViewBag.infodata = tea;
            return View(sdetailvm);
        }
        [HttpPost]
        public void updatetea(int task_id, int teaid)
        {
            string state = "已完成";
            taskSer.updateteaid(task_id, teaid, state);
        }
    }
}

Tutor.UI/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using BLL;
using Tutor.UI.ViewModels;

namespace Tutor.UI.Controllers
{
    public class TeacherController : Controller
    {
        TaskService taskSer = new TaskService();
        TeacherService teacherSer = new TeacherService();
        SampleService sampleSer = new SampleService();
        CommentService commentSer = new CommentService();
        ExhibitionService exhibitionSer = new ExhibitionService();
        TeacherInfoService teacherinfoSer = new TeacherInfoService();
        AppointmentService appointmentSer = new AppointmentService();
        // GET: Teacher
        public ActionResult Index()
        {
            if (Session["user_id"].ToString() == null)
            {
                return Content("请先登录");
            }
            var Tid = (int)Session["user_id"];
            //!id.HasValue? (int)Session["user_id"] : id.Value;
            var tea = teacherSer.getteacherbyid(Tid);
            //这里本可以查询teacherinfo然后利用导航属性，但这里涉及到不止两个表，所以恐怕不行。
            var tas = taskSer.GetModels(b => b.Teacher_id == Tid);
            var appo = appointmentSer.GetModels(b => b.Teacher_id == Tid);
            TdeatilVM tdetail = new TdeatilVM();
            tdetail.tuser = tea;
            tdetail.task = tas;
            tdetail.appointment = appo;
            return View(tdetail);
        }
        public ActionResult detail(int id)
        {
            var sample = sampleSer.GetModels(b => b.Teacher_id == id);
            var tea = teacherinfoSer.GetModels(b => b.Teaher_id == id).FirstOrDefault();
            var comt = commentSer.GetModels(b => b.Teacher_id == id);
            var exhi = exhibitionSer.GetModels(b => b.Teacher_id==id);
            Tshow tshow = new Tshow();
            tshow.sample = sample;
            tshow.teaccherinfo = tea;
            tshow.comment = comt;
            tshow.exhibition = exhi;
            return View(tshow);
        }
        public void comment(Comment cm)
        {
            commentSer.Add(cm);
        }

    }
}

Tutor.UI/Views/Index/Index.cshtml
@model Tutor.UI.ViewModels.IndexVM
@*@using Model;*@

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Lauout.cshtml";
    //ViewBag.loginviewmodel = new Model.Teacher();
}
<link href="~/Css/index.css" rel="stylesheet"/>
<link href="~/Css/font-awesome.min.css" rel="stylesheet" />
<div class="firstdiv">
    <div class="selectdiv">
        <ul>
            <li>
                <div class="choose" id="choosegrade">
                    <span class="mygrade">选择年级</span>
                    <span class="fa fa-sort-desc fa-2x triangle"></span>
                    <ul>
                        @foreach (var item in Model.grade)
                        {
                                <li><span data-id="@item.Grade_id">@item.Grade1</span></li>
                        }
                    </ul>
                </div>
            </li>
            <li>
                <div class="choose" id="choosesub">
                    <span class="mysubject">选择学科</span>
                    <span class="fa fa-sort-desc fa-2x triangle"></span>
                    <ul>
                    </ul>
                </div>
            </li>
            <li>
                <a class="search button" id="mysearch" href="" style="width:80%;">搜索家教</a>
            </li>
        </ul>
    </div>
    <div class="logindiv">
        @if (Session["user_id"] == null)
        {
            @Html.Partial("_login", Model.teacher)
        }
        else
        {
            <section class="userinfo">
                <div><img src="@Session["head"].ToString()" /></div>
                <div><span>欢迎您，@Session["name"].ToString()</span></div>
                <div>
                    @if (Session["tflag"] == null)
                    {
                        <a href="@Url.Action("Index","Student")">个人中心</a>
                    }
                    else
                    {
                        <a href="@Url.Action("Index","Teacher")">个人中心</a>
                    }
                    <a href="@Url.Action("signout","Index")" target="_parent">退出</a>
                </div>
            </section>
            <div class="after">
                <div>
                    <span>公告</span>
                </div>
                <div>
                    <ul>
                        <li>
                            <span><a href="#">常见使用问题</a></span>
                            <span>5-18</span>
                        </li>
                        <li>
                            <span><a href="#">家教价格参考</a></span>
                            <span>4-28</span>
                        </li>
                        <li>
                            <span><a href="#">搜狐网报道提优特</a></span>
                            <span>5-15</span>
                        </li>
                        <li>
                            <span><a href="#">新浪网报道提优特</a></span>
                            <span>2-28</span>
                        </li>
                        <li>
                            <span><a href="#">凤凰网报道提优特</a></span>
                            <span>4-21</span>
                        </li>
                    </ul>
                </div>
            </div>
        }        
        
    </div>
</div>
<div class="title">
    <h3>推荐教员</h3>
</div>
<div class="rectea">
    <div class="grade">
        <ul class="ulmp">
            <li class="act">学前教育</li>
            <li>小学家教</li>
            <li>初中家教</li>
            <li>高中家教</li>
        </ul>
    </div>
    <div class="teadetail">
        <div class="activedetail">
            <div style="width:100%;clear:both;overflow:hidden;">
                @foreach (var item in Model.kidtea)
                 {
                    <div class="singletea">
                        <div>
                            <img src="@item.Teacher.Tphoto" />
                        </div>
                        <div>
                            <ul class="ulmp">
                                <li><a href="@Url.Action("detail","Teacher",new { id=@item.Teaher_id})"}>@item.Teacher.Tuser_name</a></li>
                                <li>@item.Available_subject</li>
                                <li>@item.Description</li>
                            </ul>
                        </div>
                    </div>
                 }
            </div>
        </div>
        <div class="">
            @foreach (var item in Model.pretea)
            {
                <div>
                    <div class="singletea">
                        <div>
                            <img src="@item.Teacher.Tphoto" />
                        </div>
                        <div>
                            <ul class="ulmp">
                                <li><a href="@Url.Action("detail","Teacher",new { id=@item.Teaher_id})" }>@item.Teacher.Tuser_name</a></li>
                                <li>@item.Available_subject</li>
                            </ul>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="">
            @foreach (var item in Model.midtea)
            {
                <div>
                    <div class="singletea">
                        <div>
                            <img src="@item.Teacher.Tphoto" />
                        </div>
                        <div>
                            <ul class="ulmp">
                                <li><a href="@Url.Action("detail","Teacher",new { id=@item.Teaher_id})" }>@item.Teacher.Tuser_name</a></li>
                                <li>@item.Available_subject</li>
                                <li>@item.Description</li>
                            </ul>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="">
            @foreach (var item in Model.higtea)
            {
                <div>
                    <div class="singletea">
                        <div>
                            <img src="@item.Teacher.Tphoto" />
                        </div>
                        <div>
                            <ul class="ulmp">
                                <li><a href="@Url.Action("detail","Teacher",new { id=@item.Teaher_id})">@item.Teacher.Tuser_name</a></li>
                                <li>@item.Available_subject</li>
                                <li>@item.Description</li>
                            </ul>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<div class="title">
    <h3>推荐家教</h3>
</div>
<div class="task">
    @foreach(var item in Model.task)
    {
        <div class="singlecase">
            <div class="Ttop">
                <div>@item.Student.Suser_name 急需家教</div>
                <div>辅导 @item.Subject</div>
                <div>
                    <strong>面议</strong>
                </div>
            </div>
            <div class="Tbottom">
                <span class="fa fa-location-arrow"></span>
                <span>@item.Location</span>
                <div>等待您来应聘</div>
                <button id="appo" data-id="@item.Task_id" class="button ypbutton"><span>我要应聘</span></button>
            </div>
        </div>
    }
</div>
<div class="hidden" style="display:none">@Session["user_id"]</div>
<script src="~/scripts/jquery-3.3.1.js"></script>
<script>
    var idd = $(".hidden").text();
    //choosegrade
    $("#choosegrade").hover(function () {
        $("#choosegrade>ul").css({ "display": "block", "background-color": "white", "z-index": "100", "cursor": "pointer" });
    }).click(function (event) {
        var grade = event.target.innerText;
        $("#choosegrade>span:first-child").text(grade);
    }).mouseleave(function () {
        $("#choosegrade>ul").css("display", "none");
    });

    //choosesubject
    $("#choosesub").hover(function () {
        $("#choosesub>ul").css({ "display": "block", "background-color": "white", "z-index": "100", "cursor": "pointer" });
    }).click(function (event) {
        var subject = event.target.innerText;
        $("#choosesub>span:first-child").text(subject);
    }).mouseleave(function () {
        $("#choosesub>ul").css("display", "none");
    })

    //loginbox
    $(".choosebar span:nth-child(1)").hover(function () {
        $(".teacherbox").css("display", "block");
        $(".studentbox").css("display", "none");
        $(".choosebar span:nth-child(1)").css("border", "none");
        $(".choosebar span:nth-child(2)").css({ "border-bottom": "1px solid lightgray", "border-left": "1px solid lightgray" });
    });
    $(".choosebar span:nth-child(2)").hover(function () {
        $(".studentbox").css("display", "block");
        $(".teacherbox").css("display", "none");
        $(".choosebar span:nth-child(2)").css("border", "none");
        $(".choosebar span:nth-child(1)").css({"border-bottom":"1px solid lightgray","border-right":"1px solid lightgray"})
    })

    //获取年级和科目的数据
    $("#choosegrade ul li span").click(function (event) {
        var grade_id = event.currentTarget.dataset.id;
        var grade = event.currentTarget.innerText;
        $.get("/Index/getsubject/" + grade_id, function (data) {
            $("#choosesub ul").empty();
            for (var x in data) {
                var sub = $("<li></li>").text(data[x].subject1);
                $("#choosesub ul").append(sub);
            }
        })
    })

    //搜索跳转功能
    var subject1 = '';
    $("#choosesub").hover(function () {
        $("#choosesub ul li").click(function (event) {
            subject1 = event.currentTarget.innerText;
            $("#mysearch").attr("href","/Search/searchredir/?subject="+subject1);
        });
    });
    //$(".appo").click(function () {
    //    if (idd == '') {
    //        console.log("1");
    //        alert("请先登录");
    //    }
    //})
    //    $.post("/Search/searchredir/", {
    //        subject:subject1,
    //    })
    

    //控制推荐家教的展示
    var tabs = document.querySelectorAll('.grade ul li');
    var content = document.querySelectorAll('.teadetail>div');
    for (i = 0; i < tabs.length; i++) {
        var tab = tabs[i];
        settabhand(tab, i);
    }
    function settabhand(tab, tabpos) {
        tab.onmouseover = function () {
            for (i = 0; i < tabs.length; i++) {
                tabs[i].className = '';
            }
            tab.className = 'act';
            for (i = 0; i < content.length; i++) {
                content[i].className = '';
            }
            content[tabpos].className = 'activedetail';
        }
    }

    //应聘家教
    $(".ypbutton").click(function (event) {
        if (idd == '') {
            alert("请先登录");
        }
        else {
            var mydate = new Date().toLocaleDateString();
            var taskid = event.currentTarget.dataset.id;
            var state = "预约成功";
            $.post("/search/makeorder/", {
                Teacher_id: idd,
                task_id: taskid,
                atime: mydate,
                astate: state
            }, function (data) {
                alert(data);
            })
        }
        
    })
</script>

Tutor.UI/Views/Index/_login.cshtml
@*@model Model.Teacher*@
@{ 
    Model.Teacher teachervm = ViewBag.loginviewmodel;
}
<div class="before">
    <div class="choosebar">
        <span>教员登录</span>
        <span>学员登录</span>
    </div>
    <div class="inputbox">
        <div class="teacherbox">
            @using (Html.BeginForm("teacherlogin", "Index", FormMethod.Post))
            {
                <ul>
                    <li>
                        <label>用户名</label>
                        @*@Html.TextBoxFor(t => teachervm.Tuser_name, new { placeholder = "请输入教员账号", @class = "pad", type = "text" })*@
                        <input class="pad" id="teachervm_Tuser_name" name="Tuser_name" type="text" placeholder="请输入教员账号"/>
                    </li>
                    <li>
                        <label>密 &nbsp; 码</label>
                        @*@Html.TextBoxFor(t => teachervm.Tpwd, new { placeholder = "请输入密码", @class = "pad", type = "password" })*@
                        <input class="pad" id="teachervm_Tpwd" name="Tpwd" type="password" placeholder="请输入密码" autocomplete="on"/>
                    </li>
                    <li>
                        <input type="checkbox" />记住我的登录状态
                    </li>
                    <li>
                        <input type="submit" value="登录"  class="tdbutton"/>
                    </li>
                </ul>
            }
        </div>
        <div class="studentbox" style="display:none;">
                @using (Html.BeginForm("studentlogin", "Index", FormMethod.Post))
                {
                    <ul>
                        <li>
                            <label>用户名</label>
                            <input class="pad" type="text" name="Suser_name" placeholder="请输入学员账号" />
                        </li>
                        <li>
                            <label>密 &nbsp; 码</label>
                            <input class="pad" type="password" name="Spwd" placeholder="请输入密码" autocomplete="on" />
                        </li>
                        <li>
                            <input type="checkbox" />记住我的登录状态
                        </li>
                        <li>
                            <input type="submit" value="登录"  class="tdbutton"/>
                        </li>
                    </ul>
                }
        </div>
    </div>
    <div class="regbox">
        <a href="/Account/register/">学员注册</a>
        <a href="#">教员注册</a>
    </div>
</div>

Tutor.UI/Views/Index/searchresult.cshtml
@{
    ViewBag.Title = "searchresult";
    Layout = "~/Views/Shared/_Lauout.cshtml";
}
<link href="~/Css/searchresult.css" rel="stylesheet"/>
<div>
    <div class="searchbar">
        <div class="area">
            <strong>所在区域</strong>
            <div>
                <ul class="ulmp">
                    <li>从数据库查出所有老师available的区域去重展示</li>
                </ul>
            </div>
        </div>
        <div class="area">
            <strong>性别要求</strong>
            <div>
                <ul class="ulmp">
                    <li>不限</li>
                    <li>男</li>
                    <li>女</li>
                </ul>
            </div>
        </div>
    </div>
    
    <div class="result">
        <div class="singleresult">
            <div>
                <img src="~/Img/登录注册/rg.jpg" style="width:120px;height:120px;" />
            </div>
            <div>
                <p style="margin-top:0;">刘强东</p>
                <div>
                    <span>家教经验</span>
                    <strong>2年</strong>
                    <span>课时费</span>
                    <strong>50</strong>
                </div>
                <div>
                    <span>学校专业</span>
                    <strong>江西师范大学</strong>
                </div>
                <div>
                    <span>教授科目</span>
                    <strong>小学语文，高中英语</strong>
                </div>
                <div>
                    <span>接受区域</span>
                    <strong>青山湖区</strong>
                </div>
                <div>
                    <span>个人简介</span>
                    <strong>大家好，我叫刘强bababab</strong>
                </div>
            </div>
        </div>
    </div>
</div>